# -*- coding: utf-8 -*-
"""aula16-02.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UdUrya7RNpt7tRGIxjY6YzXSflO3HteO
"""

print("Olá estou no acampamento Python") #strings são palavras
print(2+2)
print(2*3 / (4/5) + 9**2) 
print("Olá eu tenho 34 / 2 laranjas \n") #\n é um caracter de escape salte um linha
print("O resultado da operação 9**3 = ",9**3,"\ne o valor de 9**4",9**4)

"""O objetivo construir um algoritmo que calcule a velocidade de um corpo dados seu deslocamento e tempo"""

x = 30 #x é o nome da variável e 30 é seu valor ou conteúdo
nome = "sarah" #atribuir a variável nome o valor sarah ou então nome recebe sarah
# nome s de variável NÃO pode ter espaço, acento, caracter especial
var_1 = 123.8 #Tem que usar ponto não vírgula
print(var_1)

print(type(x))
print(type(var_1))

distancia = 30.2e6 #30.2 vezes 10 elevado a 6
tempo = 456.87 #float são números decimais
velocidade = distancia/tempo
print("A velocidade do corpo é de", velocidade,"m/s")
#para retirar as casas decimais vamos usar formatação de strings
print(f"A velocidade do corpo é de {velocidade} m/s")
print(f"A velocidade do corpo é de {velocidade:.2f} m/s")
print(f"A velocidade do corpo é de {velocidade:.2e} m/s")

import math
print(math.cos(math.degrees(33)))
print(math.cos(math.radians(33)))
print(f"o fatorial de 12 é {math.factorial(12)}")

"""

Crie um algoritmo em Python que execute as seguintes tarefas:  Armazene em uma variável a quantidade de dias em um ano (não bissexto); Calcule e armazene em outra variável a quantidade de horas em um ano; Calcule e armazene em outra variável a quantidade de minutos em um ano;
Calcule e armazene em outra variável a quantidade de segundos em um ano;

Mostre na tela uma mensagem do tipo

Um ano tem ... dias, ... horas, ... minutos e ...segundos;
"""

x = 365
var_1 = 365 * 24
var_2 = var_1 * 60
var_3 = var_2 * 60
print(f"Um ano tem {x} dias, {var_1} horas, {var_2} minutos e {var_3} segundos")

"""Vamos calcular agora o índice de massa corporal"""

# o IMC é calculado como IMC = peso/altura
# vamos usar float() para converter para decimal
# vamos usar int() para converter para inteiro
peso = float(input("Digite o seu peso: "))
altura = float(input("Digite a sua altura: "))
IMC = peso/altura**2
print("O seu IMC é:",IMC)

"""Crie um algoritmo em Python que solicite ao usuário para digitar o valor total de uma compra de supermercado. Depois peça ao usuário para digitar (separadamente) a quantidade de notas de 50, 20, 10 e 5 reais fornecidas pelo cliente. Por fim o algoritmo deve mostrar o valor do troco a ser dado ao cliente

Veja exemplo de execução ao lado. (valores em vermelho são digitados pelo usuário)

"""

compra = float(input("Digite o valor da compra: R$ "))
notas50 =   int(input("Digite a quantidade de notas de R$50,00: "))
notas20 =   int(input("Digite a quantidade de notas de R$20,00: "))
notas10 =   int(input("Digite a quantidade de notas de R$10,00: "))
notas5 =   int(input("Digite a quantidade de notas de R$5,00: "))
pago =  (50 * notas50 + 20 * notas20 + 10 * notas10 + 5 * notas5)
diferença = pago - compra
print(f"Prezado cliente sua compra foi de R$ {compra:.2F}, você entregou R$ {pago:.2F} e seu troco é de R$ {diferença:.2F}")