# -*- coding: utf-8 -*-
"""9-3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yXEPJMwNJGCb0WYURIRKIoEdmBMDlHWr
"""

n1 = float(input("Digite a nota da primeira prova: "))
n2 = float(input("Digite a nota da segunda prova: "))
n3 = float(input("Digite a nota da terceira prova: "))
media = (n1+n2+n3) / 3
print(f"Sua média foi de: {media:.2f}" )
if (media >= 70):
    print("Você foi aprovado!")
else:
    print("Você foi reprovado!")

"""Agora para o aluno ser aprovado vamos considerar também a frequência. Se o aluno tiver 75% ou mais de frequência ele será aprovado. Mas ainda vale o critério da nota."""

n1 = float(input("Digite a nota da primeira prova: "))
n2 = float(input("Digite a nota da segunda prova: "))
n3 = float(input("Digite a nota da terceira prova: "))
freq = float(input("Digite a frequência(%): "))
media = (n1+n2+n3) / 3
print(f"Sua média foi de: {media:.2f} e a frequência foi {freq:.1f}" )
if media >= 70 and freq >=75:
    print("Você foi aprovado!")
else:
    print("Você foi reprovado!")

print('Sérgio' > 'Luana') #comparando ordem alfabética S vem depois do L então S >L

"""Fazer um algoritmo que coloque na tela a mensagem: Eu uso L'Oreal"""

print("Eu uso L'oreal")
query = ("SELECT DataInicio FROM Cursos Where CursoData > '2022-01-01'")

nome1 = input("Digite o primeiro nome: ")
nome2 = input("Digite o primeiro nome: ")
nome3 = input("Digite o primeiro nome: ")
if nome1 <= nome2 and nome2 <= nome3:
  print("Está em ordem")
else:
  print("Não está em ordem..")

n1 = float(input("Digite a nota 1: "))
n2 = float(input("Digite a nota 2: "))
n3 = float(input("Digite a nota 3: "))
freq = float(input("Digite a frequência(%): ")) #quanto por cento das aulas o aluno frequentou?
media = (n1+n2+n3)/3

print(f"Sua nota final foi: {media:.1f} e a frequ~encia foi {freq:.1f}.")

if freq < 75:
  print("Aluno Reprovado por frequência.")
elif media < 40:
  print("Você foi reprovado com conceito E")
elif media < 70:
  print("Você está exame especial seu conceito é D")
elif media < 80:
  print("Você está aprovado com conceito C")
elif media < 90:
  print("Você está aprovado com conceito B")
else:
  print("Você é estrela conceito A!")

Jogador1 = input("Joga? ")
Jogador2 = input("Joga? ")

if Jogador1 == 'r' and Jogador2 =='t':
  print("Jogador 1 venceu!")
elif Jogador1 == 't' and Jogador2 =='r':
  print("Jogador 2 venceu!")
elif Jogador1 == 'p' and Jogador2 =='r':
  print("Jogador 1 venceu!")
elif Jogador1 == 'r' and Jogador2 =='p':
  print("Jogador 2 venceu!")
elif Jogador1 == 'r' and Jogador2 =='r':
  print("Deu empate!")
elif Jogador1 == 't' and Jogador2 =='t':
  print("Deu empate!")
elif Jogador1 == 'p' and Jogador2 =='p':
  print("Deu empate!")
else:
  print("Símbolos inválidos foram digitados")