# -*- coding: utf-8 -*-
"""tarefa1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qmgXBfsDy0jVI-fcMhMGRUXm9kqCO0N7
"""

Jogador1 = input("Joga? ")
Jogador2 = input("Joga? ")

if Jogador1 == 'r' and Jogador2 =='t':
  print("Jogador 1 venceu!")
elif Jogador1 == 't' and Jogador2 =='r':
  print("Jogador 2 venceu!")
elif Jogador1 == 'p' and Jogador2 =='r':
  print("Jogador 1 venceu!")
elif Jogador1 == 'r' and Jogador2 =='p':
  print("Jogador 2 venceu!")
elif Jogador1 == 'r' and Jogador2 =='r':
  print("Deu empate!")
elif Jogador1 == 't' and Jogador2 =='t':
  print("Deu empate!")
elif Jogador1 == 'p' and Jogador2 =='p':
  print("Deu empate!")
else:
  print("Símbolos inválidos foram digitados")