# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DzRsZpEtaY3qaNSthKoXTq2UF2dGKMvq
"""

val = float(input("Digite o valor da compra:"))
n50 = int(input("Digite a qtd de notas R$50:"))
n20 = int(input("Digite a qtd de notas R$20:"))
n10 = int(input("Digite a qtd de notas R$10:"))
n5 = int(input("Digite a qtd de notas R$5:"))


dinheiro = n50*50 + n20*20 + n10*10 + n5*5
troco = dinheiro - val

if troco >= 0:
  print(f"Sua compra de foi de R${val:.2f} o cliente forneceu R$ {dinheiro:.2f} e seu troco é de R${troco:.2F}")
else:
  print(f"Sua compra de foi de R${val:.2f} o cliente forneceu R$ {dinheiro:.2f} sendo insuficiente este valor")

#objetivo calcular a raiz quadrada
import math

x = float(input("Digite um número real: "))

if x >= 0: #se x for maior que 0 faça o que está a seguir
  y = math.sqrt(x) #math.sqrt() tira a  raiz quadrada 

  print("A raiz é: ",y) 
else: #senão...caso contrário faça  que está a seguir
  print("Não existe raiz número negativo")
print("quando essa linha será executada")

# a tecla tab gera uma identação

etanol = float(input("Digite o preço do etanol: "))
gasolina = float(input("Digite o preço da gasolina: "))
x = (etanol / gasolina) * 100
print(f"O preço do etanol está {x:.2f} % do preço da gasolina")
if (x > 70):
  print("Abasteça com gasolina.")
else:
  print("Abasteça com etanol.")

n1 = float(input("Digite a nota da primeira prova: "))
n2 = float(input("Digite a nota da segunda prova: "))
n3 = float(input("Digite a nota da terceira prova: "))
media = (n1+n2+n3) / 3
print(f"Sua média foi de: {media:.2f}" )
if (media >= 70):
    print("Você foi aprovado!")
else:
    print("Você foi reprovado!")