# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HAZ4hsTllgKRb_dBjt-fsJe8PiPoDagn
"""

print("Estou no acampamento Python!!")
print(30/1+5)

print("Vejam como isso funciona")